### ISSUE TITLE
Doesn't appears as in the screenshots

### ISSUE THREAD

**Issue by Idrocf** [dragon-archer/paradox-highlight#1]
Hi, I may be doing something wrong but after I installed the extension and set the theme to Paradox Dark, it doesn't really change the highlighting for my files (yaml)

**Comment by dragon-archer** [comment]
It seems that your screenshots might not be uploaded correctly, at least I can't see them here.

In the other hand, I guess you may use the extension to highlight localization files as you mentioned the type is yaml. If so, then I'd like to ask if you have any `dynamic block` in the localization (like those quoted in `[]` or `$$`), since this extension only highlight these specific patterns while keep other plain text as is
